controller:
  serviceType: LoadBalancer
  installPlugins:
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    - configuration-as-code:latest
persistence:
  enabled: true
  existingClaim: custom-jenkins-pvc
